# Dependabot configuration for GitHub Actions
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Monitor conventional-commits action
  - package-ecosystem: "github-actions"
    directory: "/conventional-commits"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
      - "github-actions"
    
  # Monitor organization-members action
  - package-ecosystem: "github-actions"
    directory: "/organization-members"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
      - "github-actions"
    
  # Monitor transistor-subscriber-check action
  - package-ecosystem: "github-actions"
    directory: "/transistor-subscriber-check"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
      - "github-actions"
    
  # Monitor transistor-subscribers action
  - package-ecosystem: "github-actions"
    directory: "/transistor-subscribers"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
      - "github-actions"
