name: Organization members
description: Outputs a list of organization members

inputs:
  github_token:
    description: 'GitHub token to use query for organization members'
    required: true
    default: ${{ github.token }}
  organization:
    description: 'Organization to query for members'
    required: true

runs:
  using: "composite"
  steps:
    - name: Get organization members
      id: get_members
      uses: actions/github-script@v8
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const fs = require('fs');
          const inputs = ${{ toJSON(inputs) }};

          async function getAllMembers(org) {
            const members = [];
            const memberIterator = github.paginate.iterator(github.rest.orgs.listMembers, {
                org: org,
                per_page: 100
              }
            );
            for await (const response of memberIterator) {
              members.push(...response.data.map(member => ({
                login: member.login,
                id: member.id,
                type: member.type,
                site_admin: member.site_admin
              })));
            }

            return members;
          }
          
          try {
            const members = await getAllMembers(inputs.organization);
            
            // Write results to a JSON file
            fs.writeFileSync('organization-members.json', JSON.stringify(members, null, 2));

            const logins = members.map(member => member.login).join('\n');
            fs.writeFileSync('organization-members.txt', logins);

            console.log(`Successfully retrieved ${members.length} organization members`);
          } catch (error) {
            core.setFailed(`Error fetching organization members: ${error.message}`);
          }
    - name: Upload members.json
      uses: actions/upload-artifact@v5
      with:
        name: organization-members.json
        path: organization-members.json
    - name: Upload members.txt
      uses: actions/upload-artifact@v5
      with:
        name: organization-members.txt
        path: organization-members.txt

